services:

  ecommerce-damitymo:
    build:  
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/src
    env_file:
      - .env.development

    networks:
      - ecommerce-damitymo-network

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: newpassword
      POSTGRES_DB: eCommerce
    ports:
      - "5432:5432"
    networks:
      - ecommerce-damitymo-network
      
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: tymoszukdamiandejesus@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '8080:80'
    networks: 
      - ecommerce-damitymo-network
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  ecommerce-damitymo-network:
    driver: bridge