name: render-deploy-ecommerce-backend

on:
  push:
    branches: main
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      ##upload to docker hub
      
      - name: Set up docker build
        uses: docker/setup-buildx-action@v1

      - name: Log in to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/nestjs-backend-ecommerce:1.0

          ## Deploy to render

      - name: deploy to render
        uses: jphnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{secrets.RENDER_SERVICE_ID}}
          api-key: ${{secrets.RENDER_API_KEY}}
          wait-for-success: true
        

       
